language: ruby
rvm:
  - 2.2.1
gemfile:
  - Gemfile
notifications:
  email: false
script: bundle exec rspec spec
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq libav-tools libcurl3 libcurl3-gnutls libcurl4-openssl-dev
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/application.yml.travis config/application.yml
