development:
  adapter: postgresql
  encoding: unicode
  database: curlv_development
  pool: 5
  username: asiniy

test:
  adapter: postgresql
  encoding: unicode
  database: curlv_test
  pool: 5
  username: asiniy
